// Parser and generator for Canonical SOS Category URLs and SOV Keywords (2024 & 2025)
import fs from 'fs';

const rawUrls2024 = [
  "https://br-store.acer.com/336?layout=grid-2&map=productClusterIds",
  "https://br-store.acer.com/notebooks/convencional",
  "https://br-store.acer.com/notebooks/gamer",
  "https://br-store.acer.com/notebooks/ultrafino",
  "https://br-store.acer.com/notebooks/windows-11?initialMap=c&initialQuery=notebooks&map=category-1,sist--operacional&",
  "https://br-store.acer.com/vero?_q=vero&map=ft",
  "https://detail.tmall.com/item.htm?",
  "https://global.gmarket.co.kr/item?goodscode=1577413717",
  "https://global.gmarket.co.kr/item?goodscode=2056452588",
  "https://jp.ext.hp.com/desktops/personal/",
  "https://jp.ext.hp.com/desktops/personal/envy_te01_1000/",
  "https://jp.ext.hp.com/desktops/personal/hp_aio_22_intel/",
  "https://jp.ext.hp.com/desktops/personal/hp_aio_24_df0000/",
  "https://jp.ext.hp.com/desktops/personal/hp_slim_s01/",
  "https://jp.ext.hp.com/desktops/personal/pavilion_tp01/",
  "https://jp.ext.hp.com/gaming/personal/omen_16_c/",
  "https://jp.ext.hp.com/gaming/personal/omen_17_ck/",
  "https://jp.ext.hp.com/gaming/personal/omen_25l_30l/",
  "https://jp.ext.hp.com/gaming/personal/pavilion_gaming_tg01/",
  "https://jp.ext.hp.com/gaming/personal/victus_16_d/",
  "https://jp.ext.hp.com/gaming/personal/victus_16_e/",
  "https://jp.ext.hp.com/notebooks/personal/",
  "https://jp.ext.hp.com/notebooks/personal/chromebook_x360_13c/",
  "https://jp.ext.hp.com/notebooks/personal/chromebook_x360_14c/",
  "https://jp.ext.hp.com/notebooks/personal/envy_14_eb0000/",
  "https://jp.ext.hp.com/notebooks/personal/envy_15_ep/",
  "https://jp.ext.hp.com/notebooks/personal/envy_15_x360_ee0000/",
  "https://jp.ext.hp.com/notebooks/personal/envy_x360_13_bd0000/",
  "https://jp.ext.hp.com/notebooks/personal/envy_x360_15_ed1000/",
  "https://jp.ext.hp.com/notebooks/personal/hp_15s_du1000/",
  "https://jp.ext.hp.com/notebooks/personal/hp_15s_eq1000/",
  "https://jp.ext.hp.com/notebooks/personal/hp_15s_fq0000/",
  "https://jp.ext.hp.com/notebooks/personal/hp_17s_cu/",
  "https://jp.ext.hp.com/notebooks/personal/pavilion_15_eg0000/",
  "https://jp.ext.hp.com/notebooks/personal/pavilion_15_eh0000/",
  "https://jp.ext.hp.com/notebooks/personal/pavilion_aero_13_be/",
  "https://jp.ext.hp.com/notebooks/personal/pavilion_x360_14_dy/",
  "https://jp.ext.hp.com/notebooks/personal/spectre_x360_14_ea0000/?intid=spectre_spectre",
  "https://list.jd.com/list.html?cat=670%2C671%2C672&",
  "https://list.jd.com/list.html?cat=670%2C671%2C673&",
  "https://lista.mercadolivre.com.br/informatica/pc-mesa/desktop_NoIndex_True",
  "https://lista.mercadolivre.com.br/notebooks",
  "https://listado.mercadolibre.cl/desktop",
  "https://listado.mercadolibre.cl/laptop",
  "https://listado.mercadolibre.com.co/desktop",
  "https://listado.mercadolibre.com.co/laptop",
  "https://listado.mercadolibre.com.mx/desktop",
  "https://listado.mercadolibre.com.mx/laptop",
  "https://www.amazon.ca/s?i=electronics&rh=n%3A677250011&fs=true&",
  "https://www.amazon.ca/Laptop-Computers-Accessories/s?i=electronics&rh=n%3A677252011&fs=true&",
  "https://www.amazon.co.uk/s?i=computers&rh=n%3A428651031&fs=true",
  "https://www.amazon.co.uk/s?i=computers&rh=n%3A429886031&fs=true",
  "https://www.amazon.com.br/s?rh=n%3A16364751011&fs=true&ref=lp_16364751011_sar",
  "https://www.amazon.com.br/s?rh=n%3A16364755011&fs=true&ref=lp_16364755011_sar",
  "https://www.amazon.com.mx/s?rh=n%3A10189661011&fs=true&ref=lp_10189661011_sar",
  "https://www.amazon.com.mx/s?rh=n%3A10189669011&fs=true&ref=lp_10189669011_sar",
  "https://www.amazon.com/s?rh=n%3A565098&fs=true&ref=lp_565098_sar",
  "https://www.amazon.com/s?rh=n%3A565108&fs=true&ref=lp_565108_sar",
  "https://www.amazon.de/s?rh=n%3A427954031&fs=true&ref=lp_427954031_sar",
  "https://www.amazon.de/s?rh=n%3A427957031&fs=true&ref=lp_427957031_sar",
  "https://www.amazon.es/s?rh=n%3A937994031&fs=true&ref=lp_937994031_sar",
  "https://www.amazon.es/s?rh=n%3A938008031&fs=true&ref=lp_938008031_sar",
  "https://www.amazon.fr/b/?node=13829939031",
  "https://www.amazon.fr/s?rh=n%3A429879031&fs=true&ref=lp_429879031_sar",
  "https://www.amazon.in/s?i=computers&rh=n%3A1375392031&fs=true&",
  "https://www.amazon.in/s?i=computers&rh=n%3A1375424031&fs=true&",
  "https://www.amazon.it/s?rh=n%3A2706939031&fs=true&ref=lp_2706939031_sar",
  "https://www.amazon.it/s?rh=n%3A460158031&fs=true&ref=lp_460158031_sar",
  "https://www.bestbuy.ca/en-ca/category/desktop-computers/20213",
  "https://www.bestbuy.ca/en-ca/category/laptops-macbooks/20352",
  "https://www.bestbuy.com/site/desktop-computers/all-desktops/pcmcat143400050013.c?id=pcmcat143400050013",
  "https://www.bestbuy.com/site/laptop-computers/all-laptops/pcmcat138500050001.c?id=pcmcat138500050001",
  "https://www.boulanger.com/c/tous-les-ordinateurs-de-bureau",
  "https://www.boulanger.com/c/tous-les-ordinateurs-portables",
  "https://www.costco.com/desktops-servers.html",
  "https://www.costco.com/laptops.html",
  "https://www.coupang.com/np/categories/497135",
  "https://www.coupang.com/np/categories/497136",
  "https://www.currys.co.uk/gbuk/computing/desktop-pcs/desktop-pcs/317_3055_30057_xx_xx/xx-criteria.html",
  "https://www.currys.co.uk/gbuk/computing/laptops/laptops/315_3226_30328_xx_xx/xx-criteria.html",
  "https://www.elgiganten.dk/search/Desktop?context=erhverv",
  "https://www.elgiganten.dk/search/laptop?context=erhverv",
  "https://www.elgiganten.se/datorer-kontor/datorer/laptop",
  "https://www.elgiganten.se/search/Desktop",
  "https://www.elkjop.no/pc-datautstyr-og-kontor/datamaskiner/barbar-pc",
  "https://www.elkjop.no/pc-datautstyr-og-kontor/datamaskiner/stasjonar-pc",
  "https://www.euronics.it/informatica/computer-portatili/",
  "https://www.euronics.it/informatica/pc-desktop/",
  "https://www.expert.de/shop/unsere-produkte/computer-zubehor/notebooks/laptops",
  "https://www.expert.de/shop/unsere-produkte/computer-zubehor/pcs/desktop-pcs",
  "https://www.flipkart.com/computers/desktop-pcs/pr?sid=6bo,nl4&otracker=categorytree",
  "https://www.flipkart.com/laptops/pr?sid=6bo,b5g&otracker=categorytree",
  "https://www.fnac.com/Tous-les-ordinateurs-portables/Ordinateurs-portables/nsh154425/w-4?PageIndex=1",
  "https://www.fnac.com/Tous-les-PC-de-bureau/Ordinateur-de-bureau/nsh51426/w-4?PageIndex=1",
  "https://www.jbhifi.com.au/collections/computers-tablets/desktops",
  "https://www.jbhifi.com.au/collections/computers-tablets/laptops",
  "https://www.komputronik.pl/category/5022/laptopy.html",
  "https://www.komputronik.pl/category/5801/komputery-pc.html",
  "https://www.magazineluiza.com.br/computador-e-all-in-one/informatica/s/in/micr/",
  "https://www.magazineluiza.com.br/notebook-e-macbook/informatica/s/in/ntmk/",
  "https://www.mediaexpert.pl/komputery-i-tablety/komputery-pc/komputery-stacjonarne",
  "https://www.mediaexpert.pl/komputery-i-tablety/laptopy-i-ultrabooki/laptopy",
  "https://www.mediamarkt.com.tr/tr/category/_laptop-504926.html",
  "https://www.mediamarkt.com.tr/tr/category/_masa%C3%BCst%C3%BC-bilgisayarlar-504957.html",
  "https://www.mediamarkt.de/de/category/notebooks-362.html",
  "https://www.mediamarkt.de/de/category/pcs-365.html",
  "https://www.mediamarkt.es/es/category/pc-sobremesa-161.html",
  "https://www.mediamarkt.es/es/category/port%C3%A1tiles-153.html",
  "https://www.mediaworld.it/catalogo/computer-e-smart-home/computer/notebook",
  "https://www.mediaworld.it/it/category/pc-desktop-200104.html?",
  "https://www.monsternotebook.com.tr/laptop/",
  "https://www.newegg.com/Desktop-Computers/SubCategory/ID-10?Tid=19096",
  "https://www.newegg.com/p/pl?Submit=StoreIM&Category=223&Depa=3",
  "https://www.officeworks.com.au/shop/officeworks/search?q=desktop&view=grid&page=1&sortBy=bestmatch",
  "https://www.officeworks.com.au/shop/officeworks/search?q=laptop&view=grid&page=1&sortBy=bestmatch",
  "https://www.reliancedigital.in/desktops-all-in-ones/c/S101211?searchQuery=:relevance&page=0",
  "https://www.reliancedigital.in/laptops/c/S101210?searchQuery=&page=1",
  "https://www.staples.com/Desktop-Computers/cat_CL167288",
  "https://www.staples.com/Laptops/cat_CL167289",
  "https://www.thegioididong.com/laptop?key=laptop&sc=new",
  "https://www.thegioididong.com/may-tinh-de-ban",
  "https://www.tokopedia.com/p/komputer-laptop/desktop-mini-pc/desktop-all-in-one",
  "https://www.tokopedia.com/p/komputer-laptop/laptop",
  "https://www.unieuro.it/online/Computer-e-Tablet/Computer-Portatili?dFR[categories.lvl2][0]=C12",
  "https://www.unieuro.it/online/Computer-e-Tablet/PC-Desktop-e-Monitor/PC-Desktop?dFR[categories.lvl3][0]=C1301",
  "https://www.walmart.com/browse/electronics/all-desktop-computers/3944_1089430_132982_1231618",
  "https://www.walmart.com/browse/electronics/all-laptop-computers/3944_3951_1089430_132960",
  "https://www.yodobashi.com/category/19531/?word=desktop",
  "https://www.yodobashi.com/category/19531/?word=laptop"
];

const rawUrls2025 = [
  "https://detail.tmall.com/item.htm?",
  "https://global.gmarket.co.kr/item?goodscode=1577413717",
  "https://global.gmarket.co.kr/item?goodscode=2056452588",
  "https://list.jd.com/list.html?cat=670%2C671%2C672&page=1",
  "https://list.jd.com/list.html?cat=670%2C671%2C673&page=1",
  "https://lista.mercadolivre.com.br/informatica/pc-mesa/desktop_NoIndex_True",
  "https://lista.mercadolivre.com.br/notebooks",
  "https://listado.mercadolibre.com.co/desktop#D[A:desktop]",
  "https://listado.mercadolibre.com.co/laptop#D[A:laptop]",
  "https://listado.mercadolibre.com.mx/desktop#D[A:desktop]",
  "https://listado.mercadolibre.com.mx/laptop#D[A:laptop]",
  "https://www.amazon.ca/s?rh=n%3A677250011&fs=true&ref=lp_677250011_sar",
  "https://www.amazon.ca/s?rh=n%3A677252011&fs=true&ref=lp_677252011_sar",
  "https://www.amazon.co.uk/s?i=computers&rh=n%3A428651031&fs=true",
  "https://www.amazon.co.uk/s?i=computers&rh=n%3A429886031&fs=true",
  "https://www.amazon.com.br/s?rh=n%3A16364751011&fs=true&ref=lp_16364751011_sar",
  "https://www.amazon.com.br/s?rh=n%3A16364755011&fs=true&ref=lp_16364755011_sar",
  "https://www.amazon.com.mx/s?rh=n%3A10189661011&fs=true&ref=lp_10189661011_sar",
  "https://www.amazon.com.mx/s?rh=n%3A10189669011&fs=true&ref=lp_10189669011_sar",
  "https://www.amazon.com/s?rh=n%3A565098&fs=true&ref=lp_565098_sar",
  "https://www.amazon.com/s?rh=n%3A565108&fs=true&ref=lp_565108_sar",
  "https://www.amazon.de/s?rh=n%3A427954031&fs=true&ref=lp_427954031_sar",
  "https://www.amazon.de/s?rh=n%3A427957031&fs=true&ref=lp_427957031_sar",
  "https://www.amazon.es/s?rh=n%3A937994031&fs=true&ref=lp_937994031_sar",
  "https://www.amazon.es/s?rh=n%3A938008031&fs=true&ref=lp_938008031_sar",
  "https://www.amazon.fr/b/?node=13829939031",
  "https://www.amazon.fr/s?rh=n%3A429879031&fs=true&ref=lp_429879031_sar",
  "https://www.amazon.in/s?rh=n%3A1375392031&fs=true&ref=lp_1375392031_sar",
  "https://www.amazon.in/s?rh=n%3A1375424031&fs=true&ref=lp_1375424031_sar",
  "https://www.amazon.it/s?rh=n%3A2706939031&fs=true&ref=lp_2706939031_sar",
  "https://www.amazon.it/s?rh=n%3A460158031&fs=true&ref=lp_460158031_sar",
  "https://www.bestbuy.ca/en-ca/category/desktop-computers/20213",
  "https://www.bestbuy.ca/en-ca/category/laptops-macbooks/20352",
  "https://www.bestbuy.com/site/desktop-computers/all-desktops/pcmcat143400050013.c?id=pcmcat143400050013",
  "https://www.bestbuy.com/site/laptop-computers/all-laptops/pcmcat138500050001.c?id=pcmcat138500050001",
  "https://www.biccamera.com/bc/category/?q=desktop&sg=desk",
  "https://www.biccamera.com/bc/category/?q=laptop&sg=laptop",
  "https://www.boulanger.com/c/tous-les-ordinateurs-de-bureau",
  "https://www.boulanger.com/c/tous-les-ordinateurs-portables",
  "https://www.costco.com/desktops-servers.html",
  "https://www.costco.com/laptops.html",
  "https://www.coupang.com/np/categories/497135",
  "https://www.coupang.com/np/categories/497136",
  "https://www.currys.co.uk/gbuk/computing/desktop-pcs/desktop-pcs/317_3055_30057_xx_xx/xx-criteria.html",
  "https://www.currys.co.uk/gbuk/computing/laptops/laptops/315_3226_30328_xx_xx/xx-criteria.html",
  "https://www.elgiganten.dk/search/Desktop?context=erhverv",
  "https://www.elgiganten.dk/search/laptop?context=erhverv",
  "https://www.elgiganten.se/datorer-kontor/datorer/laptop",
  "https://www.elgiganten.se/search/Desktop",
  "https://www.elkjop.no/pc-datautstyr-og-kontor/datamaskiner/barbar-pc",
  "https://www.elkjop.no/pc-datautstyr-og-kontor/datamaskiner/stasjonar-pc",
  "https://www.euronics.it/informatica/computer-portatili/",
  "https://www.euronics.it/informatica/pc-desktop/",
  "https://www.expert.de/shop/unsere-produkte/computer-zubehor/notebooks/laptops",
  "https://www.expert.de/shop/unsere-produkte/computer-zubehor/pcs/desktop-pcs",
  "https://www.flipkart.com/computers/desktop-pcs/pr?sid=6bo,nl4&otracker=categorytree",
  "https://www.flipkart.com/laptops/pr?sid=6bo,b5g&otracker=categorytree",
  "https://www.fnac.com/Tous-les-ordinateurs-portables/Ordinateurs-portables/nsh154425/w-4?PageIndex=1",
  "https://www.fnac.com/Tous-les-PC-de-bureau/Ordinateur-de-bureau/nsh51426/w-4?PageIndex=1",
  "https://www.harveynorman.com.au/computers-tablets/computers/desktops-and-all-in-one",
  "https://www.harveynorman.com.au/computers-tablets/computers/laptops",
  "https://www.jbhifi.com.au/collections/computers-tablets/desktops",
  "https://www.jbhifi.com.au/collections/computers-tablets/laptops",
  "https://www.komputronik.pl/category/5022/laptopy.html",
  "https://www.komputronik.pl/category/5801/komputery-pc.html",
  "https://www.magazineluiza.com.br/computador-e-all-in-one/informatica/s/in/micr/",
  "https://www.magazineluiza.com.br/notebook-e-macbook/informatica/s/in/ntmk/",
  "https://www.mediaexpert.pl/komputery-i-tablety/komputery-pc/komputery-stacjonarne",
  "https://www.mediaexpert.pl/komputery-i-tablety/laptopy-i-ultrabooki/laptopy",
  "https://www.mediamarkt.com.tr/tr/category/_laptop-504926.html",
  "https://www.mediamarkt.com.tr/tr/category/_masa%C3%BCst%C3%BC-bilgisayarlar-504957.html",
  "https://www.mediamarkt.de/de/category/notebooks-362.html",
  "https://www.mediamarkt.de/de/category/pcs-365.html",
  "https://www.mediamarkt.es/es/category/pc-sobremesa-161.html",
  "https://www.mediamarkt.es/es/category/port%C3%A1tiles-153.html",
  "https://www.mediaworld.it/catalogo/computer-e-smart-home/computer/notebook",
  "https://www.mediaworld.it/it/category/pc-desktop-200104.html?",
  "https://www.monsternotebook.com.tr/laptop/",
  "https://www.newegg.com/Desktop-Computers/SubCategory/ID-10?Tid=19096",
  "https://www.newegg.com/p/pl?Submit=StoreIM&Category=223&Depa=3",
  "https://www.notebooksbilliger.de/notebooks",
  "https://www.notebooksbilliger.de/pc+systeme",
  "https://www.officeworks.com.au/shop/officeworks/search?q=desktop&view=grid&page=1&sortBy=bestmatch",
  "https://www.officeworks.com.au/shop/officeworks/search?q=laptop&view=grid&page=1&sortBy=bestmatch",
  "https://www.reliancedigital.in/desktops-all-in-ones/c/S101211?searchQuery=:relevance&page=0",
  "https://www.reliancedigital.in/laptops/c/S101210?searchQuery=&page=1",
  "https://www.staples.com/Desktop-Computers/cat_CL167288",
  "https://www.staples.com/Laptops/cat_CL167289",
  "https://www.thegioididong.com/laptop?key=laptop&sc=new",
  "https://www.thegioididong.com/may-tinh-de-ban",
  "https://www.tokopedia.com/p/komputer-laptop/desktop-mini-pc/desktop-all-in-one",
  "https://www.tokopedia.com/p/komputer-laptop/laptop",
  "https://www.unieuro.it/online/Computer-e-Tablet/Computer-Portatili?dFR[categories.lvl2][0]=C12",
  "https://www.unieuro.it/online/Computer-e-Tablet/PC-Desktop-e-Monitor/PC-Desktop?dFR[categories.lvl3][0]=C1301",
  "https://www.walmart.com/browse/electronics/all-desktop-computers/3944_1089430_132982_1231618",
  "https://www.walmart.com/browse/electronics/all-laptop-computers/3944_3951_1089430_132960",
  "https://www.yodobashi.com/category/19531/?word=desktop",
  "https://www.yodobashi.com/category/19531/?word=laptop"
];

function getDomain(url) {
  try {
    const u = new URL(url);
    return u.hostname.replace('www.', '');
  } catch (e) {
    return url;
  }
}

function getFormFactor(url) {
  const l = url.toLowerCase();
  if (l.includes('desktop') || l.includes('mesa') || l.includes('bureau') || l.includes('pc-de-bureau') || l.includes('pcs') || l.includes('stasjonar') || l.includes('komputery-pc') || l.includes('may-tinh-de-ban')) {
    return 'Desktop';
  }
  return 'Laptop';
}

const categorized2024 = rawUrls2024.map((url, idx) => ({
  id: `URL-2024-${String(idx + 1).padStart(3, '0')}`,
  url,
  domain: getDomain(url),
  form_factor: getFormFactor(url),
  year: 2024,
  status: 'AUDITED'
}));

const categorized2025 = rawUrls2025.map((url, idx) => ({
  id: `URL-2025-${String(idx + 1).padStart(3, '0')}`,
  url,
  domain: getDomain(url),
  form_factor: getFormFactor(url),
  year: 2025,
  status: 'ACTIVE_LIVE'
}));

const canonicalData = {
  category_urls: {
    y2024: categorized2024,
    y2025: categorized2025,
    summary: {
      total_2024_urls: categorized2024.length,
      total_2025_urls: categorized2025.length,
      laptop_urls_2025: categorized2025.filter(u => u.form_factor === 'Laptop').length,
      desktop_urls_2025: categorized2025.filter(u => u.form_factor === 'Desktop').length,
    }
  }
};

fs.writeFileSync('./src/data/canonical_sos_category_urls.json', JSON.stringify(canonicalData, null, 2));
console.log('Saved canonical SOS Category URLs to src/data/canonical_sos_category_urls.json');
